version: "3.1"

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  exclude:
  database_postgres:
